# -*- eval: (flyspell-mode); eval: (ispell-change-dictionary "en") -*-
#+title: Install klitter
#+author: Ruben Philipp
#+date: 2024-07-27
#+startup: overview

#+begin_comment
$$ Last modified:  00:40:36 Sun Jul 28 2024 CEST
#+end_comment

* klitter

Installing /klitter/ is quite straightforward.  /klitter/ contains a proper
.asdf-file, so it can easily be loaded e.g. via quicklisp. Thus, just clone the
source code into your ~local-projects~ directory:

#+begin_src shell
# In your Quicklisp standard directory (e.g. ~/quicklisp/local-projects/)
git clone http://github.com/rubenphilipp/klitter
#+end_src

* dependencies

You'll also need a few dependencies.

** Common Lisp Music (CLM)

/klitter/ requires CLM to be installed. You can fetch the source code here:
https://ccrma.stanford.edu/software/clm/

Installation instructions for CLM (in the context of Michael Edwards's
/slippery-chicken/) can be found here:
https://github.com/mdedwards/slippery-chicken/blob/master/install.md#common-lisp-music-optional-1

** Csound

Csound is required for the synthesis of the scores generated by
/klitter/. Detailed information on how to install Csound can be found here:
https://csound.com.

** sonic-annotator

If you want to use /klitter's/ default descriptor functions for analysis, you
will need /sonic-annotator/ which you can get here:
https://vamp-plugins.org/sonic-annotator/

*** VAMP plugins

When using /sonic-annotator/ with /klitter's/ standard descriptors, you'll also
need the following VAMP-Plugins for analysis:

- [[https://www.vamp-plugins.org/plugin-doc/vamp-example-plugins.html][The VAMP Example Plugins]]
- [[https://code.soundsoftware.ac.uk/projects/vamp-libxtract-plugins][LibXtract Vamp Plugins]]


* Testing

If you have installed everything, you might want to check if /klitter/ works on
your system. The best way to do this is by running the regression tests in your
Lisp implementation:

#+begin_src lisp
(asdf:test-system :klitter)
#+end_src
